-- 1. Tabela ROLA
CREATE TABLE ROLE (
    ID_ROLI INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAZWA_ROLI VARCHAR2(50) NOT NULL UNIQUE
);

-- 2. Tabela UZYTKOWNICY
CREATE TABLE UZYTKOWNICY (
    ID_UZYTKOWNIKA INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    STOPIEN_NAUKOWY VARCHAR2(50)
);

-- 3. Tabela pośrednicząca ROLE_UZYTKOWNICY
CREATE TABLE ROLE_UZYTKOWNICY (
    ID_UZYTKOWNIKA INTEGER NOT NULL,
    ID_ROLI INTEGER NOT NULL,
    PRIMARY KEY (ID_UZYTKOWNIKA, ID_ROLI),
    CONSTRAINT FK_ROLE_UZYTKOWNIK FOREIGN KEY (ID_UZYTKOWNIKA) REFERENCES UZYTKOWNICY(ID_UZYTKOWNIKA),
    CONSTRAINT FK_ROLE_ROLA FOREIGN KEY (ID_ROLI) REFERENCES ROLE(ID_ROLI)
);

-- 4. Budynki
CREATE TABLE BUDYNKI (
    ID_BUDYNKU INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAZWA_BUDYNKU VARCHAR2(30) NOT NULL,
    ADRES VARCHAR2(50) NOT NULL
);

-- 5. Sale
CREATE TABLE SALE (
    ID_SALI INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAZWA_SALI VARCHAR2(30) NOT NULL,
    RODZAJ_SALI VARCHAR2(30) NOT NULL,
    LICZBA_MIEJSC INTEGER,
    WYPOSAŻENIE VARCHAR2(200) NOT NULL,
    ID_BUDYNKU INTEGER NOT NULL,
    CONSTRAINT FK_SALA_BUDYNEK FOREIGN KEY (ID_BUDYNKU) REFERENCES BUDYNKI(ID_BUDYNKU)
);

-- 6. Grupy cykliczne
CREATE TABLE GRUPYCYKLICZNE (
    ID_GRUPY_CYKLICZNEJ INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_START DATE NOT NULL,
    DATA_KONIEC DATE NOT NULL,
    DZIEN_TYGODNIA INTEGER NOT NULL,
    GODZINA_OD VARCHAR2(5),
    GODZINA_DO VARCHAR2(5),
    OPIS VARCHAR2(255)
);

-- 7. Przedmioty
CREATE TABLE PRZEDMIOTY (
    ID_PRZEDMIOTU INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAZWA_PRZEDMIOTU VARCHAR2(30) NOT NULL
);

-- 8. Rezerwacje
CREATE TABLE REZERWACJE (
    ID_REZERWACJI INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SALI INTEGER NOT NULL,
    ID_UZYTKOWNIKA INTEGER NOT NULL,
    ID_PRZEDMIOTU INTEGER NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    CZAS_OD TIMESTAMP WITH TIME ZONE NOT NULL,
    CZAS_DO TIMESTAMP WITH TIME ZONE NOT NULL,
    ID_GRUPY_CYKLICZNEJ INTEGER,

    -- Klucze obce
    CONSTRAINT FK_REZERWACJA_SALA FOREIGN KEY (ID_SALI) REFERENCES SALE(ID_SALI),
    CONSTRAINT FK_REZERWACJA_UZYTKOWNIK FOREIGN KEY (ID_UZYTKOWNIKA) REFERENCES UZYTKOWNICY(ID_UZYTKOWNIKA),
    CONSTRAINT FK_REZERWACJA_PRZEDMIOT FOREIGN KEY (ID_PRZEDMIOTU) REFERENCES PRZEDMIOTY(ID_PRZEDMIOTU),
    CONSTRAINT FK_REZERWACJA_GRUPA FOREIGN KEY (ID_GRUPY_CYKLICZNEJ) REFERENCES GRUPYCYKLICZNE(ID_GRUPY_CYKLICZNEJ)
);

-- 9. Tabela pośrednicząca dla UZYTKOWNICY - PRZEDMIOTY
CREATE TABLE UZYTKOWNICY_PRZEDMIOTY (
    ID_UZYTKOWNIKA INTEGER NOT NULL,
    ID_PRZEDMIOTU INTEGER NOT NULL,
    CONSTRAINT PK_UZYTKOWNICY_PRZEDMIOTY PRIMARY KEY (ID_UZYTKOWNIKA, ID_PRZEDMIOTU),
    CONSTRAINT UK_UP_ID_UZYTKOWNIKA FOREIGN KEY (ID_UZYTKOWNIKA) REFERENCES UZYTKOWNICY(ID_UZYTKOWNIKA),
    CONSTRAINT UK_UP_ID_PRZEDMIOTU FOREIGN KEY (ID_PRZEDMIOTU) REFERENCES PRZEDMIOTY(ID_PRZEDMIOTU)
)
;

