-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-23 11:18:17 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Budynki 
    ( 
     id_budynku    INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
     nazwa_budynku VARCHAR2 (30)  NOT NULL , 
     adres         VARCHAR2 (50)  NOT NULL 
    ) 
;



CREATE TABLE GrupyCykliczne 
    ( 
     id_grupy_cyklicznej INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
     data_start          DATE  NOT NULL , 
     data_koniec         DATE  NOT NULL , 
     dzien_tygodnia      INTEGER  NOT NULL , 
     godzina_od          VARCHAR2(5) ,
     godzina_do          VARCHAR(5),
     opis                VARCHAR2 (200)
    )
;



CREATE TABLE Przedmioty
    (
     id_przedmiotu    INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     nazwa_przedmiotu VARCHAR2 (30)  NOT NULL ,
     id_uzytkownika   INTEGER  NOT NULL
    )
;



CREATE TABLE Rezerwacje
    (
     id_rezerwacji       INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
     id_sali             INTEGER  NOT NULL ,
     id_uzytkownika      INTEGER  NOT NULL ,
     id_przedmiotu       INTEGER  NOT NULL ,
     status              VARCHAR2 (30)  NOT NULL ,
     czas_od             TIMESTAMP WITH TIME ZONE  NOT NULL ,
     czas_do             TIMESTAMP WITH TIME ZONE  NOT NULL ,
     id_grupy_cyklicznej INTEGER
    )
;



CREATE TABLE "ROLE"
    (
     id_roli    INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
     nazwa_roli VARCHAR2 (50)  NOT NULL
    )
;


CREATE TABLE Role_Uzytkownicy
    (
     id_roli        INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
     id_uzytkownika INTEGER  NOT NULL
    )
;



CREATE TABLE Sale
    (
     id_sali       INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
     nazwa_sali    VARCHAR2 (30)  NOT NULL ,
     rodzaj_sali   VARCHAR2 (30)  NOT NULL ,
     liczba_miejsc INTEGER ,
     wyposażenie   VARCHAR2 (200) ,
     id_budynku    INTEGER  NOT NULL
    )
;



CREATE TABLE Uzytkownicy
    (
     id_uzytkownika  INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     imie            VARCHAR2 (50)  NOT NULL ,
     nazwisko        VARCHAR2 (50)  NOT NULL ,
     stopien_naukowy VARCHAR2 (50)
    )
;



ALTER TABLE Przedmioty
    ADD CONSTRAINT Przedmiot_Uzytkownik_FK FOREIGN KEY
    (
     id_uzytkownika
    )
    REFERENCES Uzytkownicy
    (
     id_uzytkownika
    )
;

ALTER TABLE Rezerwacje
    ADD CONSTRAINT Rezerwacja_GrupaCykliczna_FK FOREIGN KEY
    (
     id_grupy_cyklicznej
    )
    REFERENCES GrupyCykliczne
    (
     id_grupy_cyklicznej
    )
;

ALTER TABLE Rezerwacje
    ADD CONSTRAINT Rezerwacja_Przedmiot_FK FOREIGN KEY
    (
     id_przedmiotu
    )
    REFERENCES Przedmioty
    (
     id_przedmiotu
    )
;

ALTER TABLE Rezerwacje
    ADD CONSTRAINT Rezerwacja_Sala_FK FOREIGN KEY
    (
     id_sali
    )
    REFERENCES Sale
    (
     id_sali
    )
;

ALTER TABLE Rezerwacje
    ADD CONSTRAINT Rezerwacja_Uzytkownik_FK FOREIGN KEY
    (
     id_uzytkownika
    )
    REFERENCES Uzytkownicy
    (
     id_uzytkownika
    )
;

ALTER TABLE Role_Uzytkownicy
    ADD CONSTRAINT Rola_Uzytkownik_Rola_FK FOREIGN KEY
    (
     id_roli
    )
    REFERENCES Role
    (
     id_roli
    )
;

ALTER TABLE Role_Uzytkownicy
    ADD CONSTRAINT Rola_Uzytkownik_Uzytkownik_FK FOREIGN KEY
    (
     id_uzytkownika
    )
    REFERENCES Uzytkownicy
    (
     id_uzytkownika
    )
;

ALTER TABLE Sale
    ADD CONSTRAINT Sala_Budynek_FK FOREIGN KEY
    (
     id_budynku
    )
    REFERENCES Budynki
    (
     id_budynku
    )
;



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0
