-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-23 11:18:17 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Budynki 
    ( 
     id_budynku    INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
     nazwa_budynku VARCHAR2 (30)  NOT NULL , 
     adres         VARCHAR2 (50)  NOT NULL 
    ) 
;



CREATE TABLE GrupyCykliczne 
    ( 
     id_grupy_cyklicznej INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
     data_start          DATE  NOT NULL , 
     data_koniec         DATE  NOT NULL , 
     dzien_tygodnia      INTEGER  NOT NULL , 
     godzina_od          TIMESTAMP WITH TIME ZONE  NOT NULL , 
     godzina_do          TIMESTAMP WITH TIME ZONE  NOT NULL , 
     opis                VARCHAR2 (200) 
    ) 
;



CREATE TABLE Przedmioty 
    ( 
     id_przedmiotu    INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
     nazwa_przedmiotu VARCHAR2 (30)  NOT NULL , 
     id_użytkownika   INTEGER  NOT NULL 
    ) 
;



CREATE TABLE Rezerwacje 
    ( 
     id_rezerwacji       INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
     id_sali             INTEGER  NOT NULL , 
     id_użytkownika      INTEGER  NOT NULL , 
     id_przedmiotu       INTEGER  NOT NULL , 
     status              VARCHAR2 (30)  NOT NULL , 
     czas_od             TIMESTAMP WITH TIME ZONE  NOT NULL , 
     czas_do             TIMESTAMP WITH TIME ZONE  NOT NULL , 
     id_grupy_cyklicznej INTEGER 
    ) 
;



CREATE TABLE Role 
    ( 
     id_roli    INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
     nazwa_roli VARCHAR2 (50)  NOT NULL 
    ) 
;


CREATE TABLE Role_Użytkownicy 
    ( 
     id_roli        INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
     id_użytkownika INTEGER  NOT NULL 
    ) 
;



CREATE TABLE Sale 
    ( 
     id_sali       INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
     nazwa_sali    VARCHAR2 (30)  NOT NULL , 
     rodzaj_sali   VARCHAR2 (30)  NOT NULL , 
     liczba_miejsc INTEGER , 
     wyposażenie   VARCHAR2 (200) , 
     id_budynku    INTEGER  NOT NULL 
    ) 
;



CREATE TABLE Użytkownicy 
    ( 
     id_użytkownika  INTEGER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
     imie            VARCHAR2 (50)  NOT NULL , 
     nazwisko        VARCHAR2 (50)  NOT NULL , 
     stopien_naukowy VARCHAR2 (50) 
    ) 
;



ALTER TABLE Przedmioty 
    ADD CONSTRAINT Przedmiot_Użytkownik_FK FOREIGN KEY 
    ( 
     id_użytkownika
    ) 
    REFERENCES Użytkownicy 
    ( 
     id_użytkownika
    ) 
;

ALTER TABLE Rezerwacje 
    ADD CONSTRAINT Rezerwacja_GrupaCykliczna_FK FOREIGN KEY 
    ( 
     id_grupy_cyklicznej
    ) 
    REFERENCES GrupyCykliczne 
    ( 
     id_grupy_cyklicznej
    ) 
;

ALTER TABLE Rezerwacje 
    ADD CONSTRAINT Rezerwacja_Przedmiot_FK FOREIGN KEY 
    ( 
     id_przedmiotu
    ) 
    REFERENCES Przedmioty 
    ( 
     id_przedmiotu
    ) 
;

ALTER TABLE Rezerwacje 
    ADD CONSTRAINT Rezerwacja_Sala_FK FOREIGN KEY 
    ( 
     id_sali
    ) 
    REFERENCES Sale 
    ( 
     id_sali
    ) 
;

ALTER TABLE Rezerwacje 
    ADD CONSTRAINT Rezerwacja_Użytkownik_FK FOREIGN KEY 
    ( 
     id_użytkownika
    ) 
    REFERENCES Użytkownicy 
    ( 
     id_użytkownika
    ) 
;

ALTER TABLE Role_Użytkownicy 
    ADD CONSTRAINT Rola_Użytkownik_Rola_FK FOREIGN KEY 
    ( 
     id_roli
    ) 
    REFERENCES Role 
    ( 
     id_roli
    ) 
;

ALTER TABLE Role_Użytkownicy 
    ADD CONSTRAINT Rola_Użytkownik_Użytkownik_FK FOREIGN KEY 
    ( 
     id_użytkownika
    ) 
    REFERENCES Użytkownicy 
    ( 
     id_użytkownika
    ) 
;

ALTER TABLE Sale 
    ADD CONSTRAINT Sala_Budynek_FK FOREIGN KEY 
    ( 
     id_budynku
    ) 
    REFERENCES Budynki 
    ( 
     id_budynku
    ) 
;